using LazurdIT.FluentOrm.Common;
using System.Runtime.CompilerServices;

namespace Samples.DAL.Models;

[FluentTable("Tbl_Class")]
public partial class ClassRecord : IFluentModel
{
    [ModuleInitializer]
    public static void Initialize()
    {
        AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
    }

    [FluentField("Fld_Class_Id", isPrimary: true, autoGenerated: true)]
    public long Id { get; set; }

    [FluentField("Fld_Class_Name")]
    public string Name { get; set; } = string.Empty;

    [FluentField("Fld_Class_Created_At")]
    public DateTimeOffset? CreatedAt { get; set; }

    [FluentField("Fld_Class_Updated_At", allowNull: true)]
    public DateTimeOffset? UpdatedAt { get; set; }

    public override string ToString()
    {
        return $"Class => Id: {Id}, Name: {Name}";
    }
}