using LazurdIT.FluentOrm.Common;
using LazurdIT.FluentOrm.Oracle;
using System.Runtime.CompilerServices;

namespace Samples.DAL.Models;

/// <summary>
/// Handles ClassName.
/// </summary>
[FluentTable("Tbl_Student")]
public partial class StudentRecord : IFluentModel
{
    [ModuleInitializer]
    public static void Initialize()
    {
        AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
    }

    [FluentField("Fld_Student_Id", isPrimary: true, autoGenerated: true, oracleDbType: FluentOracleDbTypes.Decimal)]
    public long Id { get; set; }

    [FluentField("Fld_Student_Name", oracleDbType: FluentOracleDbTypes.NVarchar2)]
    public string Name { get; set; } = string.Empty;

    [FluentField("Fld_Student_Created_At")]
    public DateTimeOffset? CreatedAt { get; set; }

    [FluentField("Fld_Student_Updated_At", allowNull: true)]
    public DateTimeOffset? UpdatedAt { get; set; }

    [FluentField("Fld_Class_Id", oracleDbType: FluentOracleDbTypes.Int64)]
    public long? ClassId { get; set; }

    public override string ToString()
    {
        return $"Student => Id: {Id}, Class Id: {ClassId}, Name: {Name}, CreatedAt: {CreatedAt}, UpdatedAt: {UpdatedAt}";
    }
}